"""Task schema models for AI processing"""
from typing import List, Optional
from datetime import datetime

from pydantic import BaseModel, Field, field_validator, model_validator

from app.models.recurrence import validate_recurrence_pattern


class TaskBaseForAI(BaseModel):
    """Base task schema generated by AI"""

    title: str = Field(
        description="Task title (multilingual allowed)"
    )

    description: Optional[str] = Field(
        None,
        description=(
            "Detailed task description (multilingual allowed). "
            "Must follow the structured format below, without omission or summarization.\n\n"

            "【Note Content】\n"
            "Transcribe ALL Note content verbatim, word-for-word. No omissions.\n\n"

            "【User Intent / Inference】\n"
            "Infer the user’s goal or intent from the Note content.\n\n"

            "【Reason / Purpose】\n"
            "Explain why this task should be executed.\n\n"

            "【What AI Should / Can Do】\n"
            "List all concrete AI contributions (research, drafting, analysis, structuring, summarization, etc.). "
            "Write \"None\" only if AI cannot contribute at all.\n\n"

            "【User–AI Collaboration Strategy】\n"
            "Define how the user and AI should collaborate, including when and what the AI prepares.\n\n"

            "【Execution Timing Rationale】\n"
            "Explain when this task should run, considering:\n"
            "- Note content and deadline\n"
            "- AI tasks: before the deadline vs exactly at the deadline\n"
            "- User tasks: when preparation should start\n"
            "- Recurring tasks: appropriate first execution time\n"
            "- No deadline: ASAP vs buffered execution\n"
            "This reasoning must match next_run_time.\n\n"

            "【Method / Steps】\n"
            "Describe how to execute the task. Multiple approaches are encouraged.\n\n"

            "Long descriptions are encouraged. Preserve the original language. "
            "Do NOT omit or summarize any information."
        )
    )

    deadline: Optional[datetime] = Field(
        None,
        description="Deadline in ISO format (e.g., 2024-10-15T00:00:00)"
    )

    status: Optional[str] = Field(
        "pending",
        description="Task status: 'pending' or 'completed'"
    )

    source_note_id: int = Field(
        description="Source Note ID (required)"
    )

    recurrence_pattern: Optional[str] = Field(
        None,
        description=(
            "Recurrence pattern: EVERY_DAY, EVERY_WEEK, EVERY_MONTH, EVERY_YEAR, "
            "EVERY_MONDAY–EVERY_SUNDAY. "
            "Multiple weekdays must be comma-separated. "
            "Set only for recurring tasks."
        )
    )

    next_run_time: datetime = Field(
        description=(
            "Next execution time in ISO format (required). "
            "AI-determined optimal timing based on Note content, deadline, and task nature. "
            "If is_ai_task=true: AI execution time. "
            "If is_ai_task=false: when the user should start preparation."
        )
    )

    is_ai_task: bool = Field(
        True,
        description=(
            "Whether AI can execute or contribute. "
            "Set true if AI can do anything. "
            "Set false ONLY if AI cannot contribute at all."
        )
    )

    @field_validator("recurrence_pattern")
    @classmethod
    def validate_recurrence_pattern_field(cls, v: Optional[str]) -> Optional[str]:
        return validate_recurrence_pattern(v)

    @model_validator(mode="after")
    def validate_recurrence_fields(self):
        # next_run_time is always required.
        # If recurrence_pattern is set → recurring task.
        # Otherwise → one-time task.
        return self


class TaskListResponse(BaseModel):
    """Task list response"""

    tasks: List[TaskBaseForAI] = Field(
        description=(
            "List of extracted tasks. Split or merge tasks based on:\n"
            "1) Different execution timing → split\n"
            "2) Different purpose or deliverable → split\n"
            "3) Different skills or responsible party → split\n"
            "4) Dependency exists → split\n"
            "5) Same timing and executor → merge\n"
            "Return an empty list if no tasks are found."
        )
    )